// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asptraining.Data;

#nullable disable

namespace asptraining.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250922025016_AddedSeedingDataDev")]
    partial class AddedSeedingDataDev
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("asptraining.Models.Developer", b =>
                {
                    b.Property<int>("DevID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DevID"));

                    b.Property<string>("DevFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevMiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DevID");

                    b.ToTable("Developer");

                    b.HasData(
                        new
                        {
                            DevID = 1,
                            DevFirstName = "Aces",
                            DevLastName = "Hapiz",
                            DevMiddleName = "Sumalinog",
                            HireDate = new DateTime(2025, 9, 22, 10, 50, 15, 329, DateTimeKind.Local).AddTicks(3069),
                            Specialty = "Full Stack Developer"
                        },
                        new
                        {
                            DevID = 2,
                            DevFirstName = "Maria",
                            DevLastName = "Lopez",
                            DevMiddleName = "Cruz",
                            HireDate = new DateTime(2025, 9, 22, 10, 50, 15, 330, DateTimeKind.Local).AddTicks(4498),
                            Specialty = "Backend Developer"
                        },
                        new
                        {
                            DevID = 3,
                            DevFirstName = "John",
                            DevLastName = "Smith",
                            DevMiddleName = "Alexander",
                            HireDate = new DateTime(2025, 9, 22, 10, 50, 15, 330, DateTimeKind.Local).AddTicks(4509),
                            Specialty = "Frontend Developer"
                        },
                        new
                        {
                            DevID = 4,
                            DevFirstName = "Sophia",
                            DevLastName = "Johnson",
                            DevMiddleName = "Grace",
                            HireDate = new DateTime(2025, 9, 22, 10, 50, 15, 330, DateTimeKind.Local).AddTicks(4511),
                            Specialty = "Mobile App Developer"
                        },
                        new
                        {
                            DevID = 5,
                            DevFirstName = "David",
                            DevLastName = "Kim",
                            DevMiddleName = "Lee",
                            HireDate = new DateTime(2025, 9, 22, 10, 50, 15, 330, DateTimeKind.Local).AddTicks(4512),
                            Specialty = "Database Administrator"
                        },
                        new
                        {
                            DevID = 6,
                            DevFirstName = "Emma",
                            DevLastName = "Brown",
                            DevMiddleName = "Claire",
                            HireDate = new DateTime(2025, 9, 22, 10, 50, 15, 330, DateTimeKind.Local).AddTicks(4513),
                            Specialty = "UI/UX Designer"
                        },
                        new
                        {
                            DevID = 7,
                            DevFirstName = "Michael",
                            DevLastName = "Garcia",
                            DevMiddleName = "Jose",
                            HireDate = new DateTime(2025, 9, 22, 10, 50, 15, 330, DateTimeKind.Local).AddTicks(4515),
                            Specialty = "DevOps Engineer"
                        },
                        new
                        {
                            DevID = 8,
                            DevFirstName = "Olivia",
                            DevLastName = "Martinez",
                            DevMiddleName = "Rose",
                            HireDate = new DateTime(2025, 9, 22, 10, 50, 15, 330, DateTimeKind.Local).AddTicks(4516),
                            Specialty = "AI/ML Engineer"
                        },
                        new
                        {
                            DevID = 9,
                            DevFirstName = "James",
                            DevLastName = "Anderson",
                            DevMiddleName = "Paul",
                            HireDate = new DateTime(2025, 9, 22, 10, 50, 15, 330, DateTimeKind.Local).AddTicks(4517),
                            Specialty = "Cybersecurity Specialist"
                        },
                        new
                        {
                            DevID = 10,
                            DevFirstName = "Liam",
                            DevLastName = "Wilson",
                            DevMiddleName = "Thomas",
                            HireDate = new DateTime(2025, 9, 22, 10, 50, 15, 330, DateTimeKind.Local).AddTicks(4518),
                            Specialty = "Cloud Solutions Architect"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
